In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")

In [3]:
supplier = pd.read_csv('supplier data.csv')
supplier.head()

,Date,Vendor,Plant Location,Category,Material Type,Defect Type,Defect,Total Defect Qty,Total Downtime Minutes
0,3/18/2018,Browsebug,Westside,Materials & Components,Glass,No Impact,Bad Bearings,929547,3983
1,11/26/2019,Topiczoom,Frazer,Mechanicals,Raw Materials,No Impact,Not Certified,760509,4749
2,10/27/2019,Zoombeat,Jordan Valley,Logistics,Carton,Rejected,Dirty,765963,396
3,4/27/2019,Buzzdog,Barling,Mechanicals,Controllers,No Impact,Warped,31166,124
4,7/6/2019,Meemm,Charles City,Logistics,Molds,No Impact,Other,706546,4038

In [4]:
supplier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5226 entries, 0 to 5225
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    5226 non-null   object
 1   Vendor                  5226 non-null   object
 2   Plant Location          5226 non-null   object
 3   Category                5226 non-null   object
 4   Material Type           5226 non-null   object
 5   Defect Type             5226 non-null   object
 6   Defect                  5226 non-null   object
 7   Total Defect Qty        5226 non-null   int64
 8   Total Downtime Minutes  5226 non-null   int64
dtypes: int64(2), object(7)
memory usage: 367.6+ KB

In [5]:
supplier.describe()

       Total Defect Qty  Total Downtime Minutes
count       5226.000000             5226.000000
mean      497251.141217             2477.725794
std       289345.287639             1433.964026
min          215.000000                0.000000
25%       247887.250000             1239.250000
50%       495020.500000             2472.500000
75%       749285.750000             3714.000000
max       999759.000000             5000.000000

In [6]:
supplier.isna().sum()

Date                      0
Vendor                    0
Plant Location            0
Category                  0
Material Type             0
Defect Type               0
Defect                    0
Total Defect Qty          0
Total Downtime Minutes    0
dtype: int64

1. Which vendors/plants are causing the greatest defect quantity?

,Date,Vendor,Plant Location,Category,Material Type,Defect Type,Defect,Total Defect Qty,Total Downtime Minutes
0,3/18/2018,Browsebug,Westside,Materials & Components,Glass,No Impact,Bad Bearings,929547,3983
1,11/26/2019,Topiczoom,Frazer,Mechanicals,Raw Materials,No Impact,Not Certified,760509,4749
2,10/27/2019,Zoombeat,Jordan Valley,Logistics,Carton,Rejected,Dirty,765963,396
3,4/27/2019,Buzzdog,Barling,Mechanicals,Controllers,No Impact,Warped,31166,124
4,7/6/2019,Meemm,Charles City,Logistics,Molds,No Impact,Other,706546,4038